- name: Mount GlusterFS volume on another node
  #This is from inventory file
  hosts: glusterfs_clients
  become: true

  vars: #Change these values If required
    # Gluster configuration.
    gluster_brick_name: gluster_volume
    #This is from inventory file
    gluster_server: glusterfs_servers

  tasks:
  - name: Install GlusterFS packages
    apt:
      name:
        - glusterfs-client
      state: present

  - name: Create mount point directory
    file:
      path: /mnt/myvolume
      state: directory
      mode: '0755'

  - name: Mount GlusterFS volume
    mount:
      name: /mnt/"{{ gluster_brick_name }}"
      src: "{{ gluster_server }}:/{{ gluster_brick_name }}"
      fstype: glusterfs
      opts: _netdev
      state: mounted
