- hosts: glusterfs-nodes
  become: true
  tasks:
    - name: Install GlusterFS server
      apt:
        name: glusterfs-server
        state: present

    - name: Start GlusterFS service
      service:
        name: glusterd
        state: started

    - name: Create GlusterFS volume
      gluster_volume:
        state: present
        name: vol1
        brick: "{{ item }}/vol1"
      with_items:
        - /mnt/brick1
        - /mnt/brick2
        - /mnt/brick3
